version: "3.2"

services:
 # Database to put tracking/stats/etc.
  trackdb:
    image: solr:8.4-slim
    ports:
     - "8983:8983"
    volumes:
#      - ${DATA_TRACKDB}:/var/solr
      - /mnt/nfs/data/trackdb:/var/solr
    entrypoint:
#      - docker-entrypoint.sh
      - solr-precreate
      - tracking
