# -------------------------------------------------------------
# This service configuration defines our main public website access stack.
# -------------------------------------------------------------

version: '3.2'

services:

  # -------------------------------------------------------------
  # Web proxy setup
  # -------------------------------------------------------------
  # All routing to sub-components goes through here.
  # All complex setup relating to the public website is here.
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro   

  # -------------------------------------------------------------
  # The main UKWA UI itself
  # -------------------------------------------------------------
  ukwa-ui:
    image: ukwa/ukwa-ui:latest
    command: java -Djava.security.egd=file:/dev/./urandom -jar /ukwa-ui.war --spring.config.location=file:/application.properties
    environment:
     - "SET_PROTOCOL_TO_HTTPS=${USE_HTTPS}"
     - "OFF_SITE_URL=https://${SERVER_NAME}/wayback/archive/"
     - "SOLR_COLLECTION_SEARCH_PATH=http://ukwa_collections:8983"
     - "SOLR_COLLECTION_SEARCH_REQUEST_HANDLER=/solr/collections/select"
     - "SOLR_FULL_TEXT_SEARCH_PATH=${SOLR_FULL_TEXT_SEARCH_PATH}"
     - "SOLR_FULL_TEXT_SEARCH_REQUEST_HANDLER=/solr/all/select"
     - "SOLR_READ_TIMEOUT=600000"
     - "SOLR_CONNECTION_TIMEOUT=60000"
     - "SOLR_USERNAME="
     - "SOLR_PASSWORD="
     - "SOLR_SHOW_STUB_DATA_SERVICE_NOT_AVAILABLE=true"
     - "BL_SMTP_SERVER_HOST=juno.bl.uk"
     - "BL_SMTP_USERNAME="
     - "BL_SMTP_PASSWORD="
    volumes:
      - ./config/ukwa-ui/ukwa-ui.properties:/application.properties:ro   

  # -------------------------------------------------------------
  # Collections index for Topics & Themes of the UKWA UI
  # -------------------------------------------------------------
  ukwa_collections:
    image: solr:6
    user: "${SOLR_UID}"
    command:
      - "solr-precreate"
      - "collections"
      - "/config/solr/collections"
    volumes:
        - "./config/solr:/config/solr"
    # Used to store the Solr index used to provide the Topic & Themes part of the main UI. Populated by an external task.
    # n.b container solr userid (8983) should have write permission on host solr dir
        - "${STORAGE_PATH}/ukwa-collections-solr/mycores:/opt/solr/server/solr/mycores"
        - "${STORAGE_PATH}/ukwa-collections-solr/logs:/opt/solr/server/logs"
    ports:
        - "9020:8983" # Exposed port so external clients can read/populate


  # -------------------------------------------------------------
  # OA Wayback configuration:
  # -------------------------------------------------------------
  pywb:
    image: ukwa/ukwa-pywb:2.4.0-beta
    environment:
      - "DEBUG=True"
      - "WEBHDFS_USER=access"
      - "UKWA_INDEX=cdx+http://cdx.api.wa.bl.uk/data-heritrix"
      - "UKWA_ARCHIVE=webhdfs://hdfs.api.wa.bl.uk"
    volumes:
      - ./config/pywb/config.yaml:/webarchive/config.yaml
      # Used to store the access control lists used by the pywb services.
      - "${STORAGE_PATH}/open-access-acl:/ukwa_pywb/acl/"


  # -------------------------------------------------------------
  # Mementos
  # -------------------------------------------------------------
  mementos:
    image: ukwa/mementoweb-webclient
    command: "/mementos/bin/mementos-webclient -Dhttp.proxyHost=${PROXYHOST} -Dhttp.proxyPort=${PROXYPORT} -Dconfig.file=/mementos/conf/application.conf -Dpidfile.path=/dev/null"
    environment:
      - "JAVA_OPTS=-Xmx1g -Dhttp.proxyHost=${PROXYHOST} -Dhttp.proxyPort=${PROXYPORT}"

  # -------------------------------------------------------------
  # Shine service and database
  # -------------------------------------------------------------
  # Shine
  shine:
   image: ukwa/shine
   environment:
     - "SOLR_URL=${SHINE_SOLR}"
     - "JAVA_OPTS=-Xmx2g -XX:+ExitOnOutOfMemoryError"
   depends_on:
     - shinedb

  # Shine state
  shinedb:
    image: postgres:9.6.2
    volumes:
      # Used to store the Shine PostgreSQL database (which hold user accounts).
      - "${STORAGE_PATH}/shine-postgres-data:/var/lib/postgresql/data"
      
      
  # -------------------------------------------------------------
  # The Python service that provides some basic APIs
  # -------------------------------------------------------------
  ukwa-access-api:
    image: ukwa/ukwa-access-api
    environment:
      - "CDX_SERVER=http://cdx.api.wa.bl.uk/data-heritrix"
      - "WEBHDFS_PREFIX=http://hdfs.api.wa.bl.uk/webhdfs/v1"
      - "KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BROKER}"
      - "KAFKA_CRAWLED_TOPIC=fc.crawled"
      - "KAFKA_SEEK_TO_BEGINNING=False"
      - "API_LABEL=UK Web Archive API"
      - "KAFKA_LAUNCH_BROKER=${KAFKA_BROKER}"
      - "KAFKA_LAUNCH_TOPIC=fc.tocrawl.npld"
      - "HTTPS_PROXY=http://194.66.232.92:3127/"
      - "SERVER_NAME=${SERVER_NAME}"
      - "ANALYSIS_SOURCE_FILE=/analysis/fc.crawled.json"
      - "SCRIPT_NAME=/api" # Deploy the API under this prefix
      - "HTTP_X_FORWARDED_PROTO=https"
    volumes:
      - "analysis-volume:/analysis"

  # Analyses recent crawl behaviour by processing the crawled data stream:
  analyse:
    image: ukwa/crawl-streams
    command: "analyse -k ${KAFKA_BROKER} -u 2 -o /analysis/fc.crawled.json"
    volumes:
      - "analysis-volume:/analysis"

  # An embedded, bannerless OA Wayback to render:
  pywb-nobanner:
    image: ukwa/ukwa-pywb:latest
    environment:
      - "WEBHDFS_USER=access"
      - "UKWA_INDEX=cdx+http://cdx.api.wa.bl.uk/data-heritrix"
      - "UKWA_ARCHIVE=webhdfs://hdfs.api.wa.bl.uk"
    volumes:
      - ./config/pywb/config-nobanner.yaml:/webarchive/config.yaml
      - ./config/pywb/empty-banner.js:/ukwa_pywb/static/default_banner.js
      # Used to store the access control lists used by the pywb services.
      - "${STORAGE_PATH}/open-access-acl:/ukwa_pywb/acl/"

  # Web page rendering post-crawl:
  webrender:
    image: ukwa/webrender-api:1.0.10
    environment:
      - "HTTP_PROXY=http://pywb-nobanner:8080"
      - "DOCKER_NETWORK=website_default"
      - "LC_ALL=en_US.utf8"
      - "WEB_RENDER_TMP=/tmp/webrender"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/webrender:/tmp/webrender
    deploy:
      replicas: 1
  

# -----------------------------------------
# Volumes and networks supporting the above
# -----------------------------------------
volumes:
  # Used to store analysis generated from Kafka, so it can be made available via the API component.
  # Only transient storage so can be managed entirely by Docker.
  analysis-volume:

networks:
  # This attachable network is needed so the screenshotter can spin up containers and talk to them over HTTP.
  # It also makes it simpler to connect to the PostgreSQL instance for maintenance.
  default:
    driver: overlay
    attachable: true

# -----------------------------------------
# Logging configuration
# -----------------------------------------
#
# Has to be done at Daemon level or service level.
#
#logging:
#  driver: gelf
#  options:
#    gelf-address: "${LOG_SERVER}"
#    tag: "${DEPLOYMENT_TAG}"

