
# This is the base configuration. 
version: '3.2'

services:

  # -------------------------------------------------------------
  # Reading Room Wayback configuration per LDL: British Library
  # -------------------------------------------------------------
  bl:
    image: ukwa/ukwa-pywb:2.4.0-beta-5
    ports:
      - "11080:8080"
    env_file: common.env
    environment:
      - "REDIS_URL=redis://bl_redis:6379/0"
    volumes:
      - ./pywb/config.yaml:/webarchive/config.yaml
      - rr-access-acl:/ukwa_pywb/acl/
    depends_on:
      - redis-bl

  # Redis service to hold locks
  bl_redis:
    image: redis:3.2.4

  # Separate service for staff access, no locks.
  bl_staff:
    image: ukwa/ukwa-pywb:2.4.0-beta-5
    ports:
      - "11090:8080"
    env_file: common.env
    volumes:
      - ./pywb/config-staff.yaml:/webarchive/config.yaml
      - rr-access-acl:/ukwa_pywb/acl/


volumes:
  # Where the access block list is held:
  rr-access-acl:

#logging:
#  driver: gelf
#  options:
#    gelf-address: "udp://logs.wa.bl.uk:12201"

